services:
  db:
    image: mysql:8.4
    container_name: nooro-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tasks
      MYSQL_USER: task-app
      MYSQL_PASSWORD: noorochallenge
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
